export const EVENTOS_RECORRENTE_TYPES = {
  ADD: "EVENTOS_RECORRENTE_ADD",
  UPDATE: "EVENTOS_RECORRENTE_UPDATE",
  DELETE: "EVENTOS_RECORRENTE_DELETE",
};

export const EVENTOS_RECORRENTE_STATE_UPDATED =
  "EVENTOS_RECORRENTE_STATE_UPDATED";
